version: '3.9'

services:
  db:
    image: mariadb:latest
    container_name: xibo
    hostname: xibo
    volumes:
      - /data/xibo/db:/var/lib/mysql:rw
      - /data/xibo/db:/etc/mysql/conf.d:rw
    env_file:
      - stack.env
    environment:
      TZ: Asia/Kuching
      MYSQL_RANDOM_ROOT_PASSWORD: true
    restart: unless-stopped

  cms-memcached:
    image: memcached:latest
    command: memcached -m 15
    container_name: xibocache
    hostname: xibo-cache
    mem_limit: 100m
    cpu_shares: 768
    read_only: true
    restart: unless-stopped

  xibo-xmr:
    image: ghcr.io/xibosignage/xibo-xmr:latest
    container_name: xibo-xmr
    hostname: xibo-xmr
    mem_limit: 256m
    cpu_shares: 768
    ports:
      - 65500:9505
    env_file:
      - stack.env
    restart: unless-stopped

  xibo-web:
    image: ghcr.io/xibosignage/xibo-cms:latest
    container_name: xibo-web
    hostname: cms-web
    mem_limit: 1g
    cpu_shares: 768
    healthcheck:
      test: wget --no-verbose --tries=1 --spider https://192.168.41.131
    ports:
      - 65501:80
    volumes:
      - /data/xibo/custom:/var/www/cms/custom:rw
      - /data/xibo/backup:/var/www/backup:rw
      - /data/xibo/theme:/var/www/cms/web/theme/custom:rw
      - /data/xibo/library:/var/www/cms/library:rw
      - /data/xibo/scripts:/var/www/cms/web/userscripts:rw
      - /data/xibo/certs:/var/www/cms/ca-certs/.*pem:rw
      - /data/xibo/certs:/var/www/cms/ca-certs/.*crt:rw
    env_file:
      - stack.env
    environment:
      XMR_HOST: xibo-xmr
      CMS_USE_MEMCACHED: true
    restart: unless-stopped
